version: 0.2

phases:
  pre_build:
    commands:
      - AWS_ACCOUNT_ID=324037300860
      - echo "Setting repository URI..."
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/taf-datastore
      - echo "Granting execute permissions to gradlew..."
      - chmod +x gradlew
      - echo "Cleaning and building the Gradle project..."
      - ./gradlew clean build
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - echo "Generating commit hash and image tag..."
      - IMAGE_TAG=build-$(date +%Y%m%d%H%M%S) # Use timestamp for unique tags
      - echo "Repository URI: $REPOSITORY_URI"
      - echo "Image tag: $IMAGE_TAG"

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t taf-datastore . # Explicit image name
      - docker tag taf-datastore:latest $REPOSITORY_URI:latest
      - docker tag taf-datastore:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing the Docker images..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Writing image definitions file..."
      - printf '[{"name":"taf-datastore","imageUri":"%s:%s"}]' $REPOSITORY_URI $IMAGE_TAG > imagedefinitions.json
      - echo "Printing imagedefinitions.json..."
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - build/libs/*.jar
